### ISSUE TITLE
Movement system

### ISSUE THREAD

**Issue by TRG-T** [J-A-F/DECREE#2]
As above. Within this task you should create a script that handles the player's movement (8 world directions). You can be blocked by #1

**Comment by TotalLolFace** [comment]
_You don't know how many time I spent on this._

What's is implemented:

- Movement system with key mapping (however we will need to write our own Input Manager in the far future),
- Basics of gravity system (it still needs a bit of corrections though),
- Jump and double jump system (also it needs a bit of correction like a gravity system),
- Template map for presentation.

We removed new input system so be sure to delete it from packet manager or download the new Dependencies folder.

Current issues;
- Problem with capsule collider (it is not a rectangle so it can sometimes block on the edge of the obstacle and it provides a strange gravitation behaviour)
- Problem with isGrounded property (it needs more Raycasts, pretty easy to fix)
- Strange behaviour of Time.deltaTime. The speed of everything is different in editor and in the build of the game, therefore use File -> Build and Run to check the proper behaviour of game physics. I will try to find out how to fix it.

I commited the task with issues due to the presentation. We will be able to show the best progress out of three groups and the issues aren't game breaking, we can easily present our work.
