### ISSUE TITLE
System of interaction with the environment

### ISSUE THREAD

**Issue by TRG-T** [J-A-F/DECREE#9]
The environment interaction system should use the sight from the weapon system (https://github.com/J-A-F/DECREE/issues/8), so I recommend writing the weapon system first.
Initially I would like the interaction button to be F, however I believe this may change in the near future. 
If you started working on this system and still didn't have a model, use a rectangle as a door.

If you have any doubts, please feel free to ask.

**Comment by TotalLolFace** [comment]
Done.

Most important things:

- Added Microsoft.CSharp csproj reference which enables i. a. very useful dynamic type for C#.
- Implemented raycasting from camera origin on "F" key ("interact" input map). The solution currently supports interacting with doors. Depending on the group name ("DoorVertical" / "DoorHorizontal"), the module handle opening and closing doors in different ways. 
- During implementation of the environment system I found a bug with movement system. When player jumps and hits the roof, they stick to the roof (for 1 or 2 seconds) instead of going down. Simple raycast looking for collision with objects above the player should fix the problem.
- Added to the main scene one wall with door opened vertically and one wall with door opened horizontally.
- To make sure that the module will work good, keep in mind to create for every next door AnimationPlayer node, which will be always a child of the parent of the static body colliding with raycast. Also don't change the node's name.

Still working on #8 but the list of items which I want to implement is so long that it will take some time.

**Comment by TRG-T** [comment]
If it is done, why there is no PR yet?
